const ShopActionsTypes = {
    FETCH_COLLECTIONS_START : 'FETCH_COLLECTIONS_START',
    FETCH_COLLECTIONS_SUCCESS : 'FETCH_COLLECTIONS_SUCCESS',
    FETCH_SHOP_FAILURE : 'FETCH_SHOP_FAILURE',
    FETCH_BRANDS_START : 'FETCH_BRANDS_START',
    FETCH_BRANDS_SUCCESS : 'FETCH_BRANDS_SUCCESS',
}


export default ShopActionsTypes